///************************************************
/// Generated by: tund
/// Date: 27/04/2012 06:58:34
/// Goal: Create User Service Class for BKINDEX_MEMBERS
///************************************************
/// <summary>
/// Create User Service Class for BKINDEX_MEMBERS
/// </summary>

namespace BKITrainingUS
{
using BKITrainingDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using System;


public class US_BKINDEX_MEMBERS : US_Object
{
	private const string c_TableName = "BKINDEX_MEMBERS";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMEMBER_NAME 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MEMBER_NAME", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MEMBER_NAME"] = value;
		}
	}

	public bool IsMEMBER_NAMENull() 
	{
		return pm_objDR.IsNull("MEMBER_NAME");
	}

	public void SetMEMBER_NAMENull() {
		pm_objDR["MEMBER_NAME"] = System.Convert.DBNull;
	}

	public DateTime datBIRTH_DAY
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "BIRTH_DAY", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["BIRTH_DAY"] = value;
		}
	}

	public bool IsBIRTH_DAYNull()
	{
		return pm_objDR.IsNull("BIRTH_DAY");
	}

	public void SetBIRTH_DAYNull()
	{
		pm_objDR["BIRTH_DAY"] = System.Convert.DBNull;
	}

	public string strGIOI_TINH_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GIOI_TINH_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GIOI_TINH_YN"] = value;
		}
	}

	public bool IsGIOI_TINH_YNNull() 
	{
		return pm_objDR.IsNull("GIOI_TINH_YN");
	}

	public void SetGIOI_TINH_YNNull() {
		pm_objDR["GIOI_TINH_YN"] = System.Convert.DBNull;
	}

	public decimal dcLEVEL_MODE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "LEVEL_MODE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["LEVEL_MODE"] = value;
		}
	}

	public bool IsLEVEL_MODENull()	{
		return pm_objDR.IsNull("LEVEL_MODE");
	}

	public void SetLEVEL_MODENull() {
		pm_objDR["LEVEL_MODE"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_BKINDEX_MEMBERS() 
	{
		pm_objDS = new DS_BKINDEX_MEMBERS();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_BKINDEX_MEMBERS(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_BKINDEX_MEMBERS(decimal i_dbID) 
	{
		pm_objDS = new DS_BKINDEX_MEMBERS();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
}
}
