///************************************************
/// Generated by: tund
/// Date: 31/03/2013 08:11:50
/// Goal: Create User Service Class for DM_LOP_IPCORE
///************************************************
/// <summary>
/// Create User Service Class for DM_LOP_IPCORE
/// </summary>

namespace BKITrainingUS
{
using BKITrainingDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using System;


public class US_DM_LOP_IPCORE : US_Object
{
	private const string c_TableName = "DM_LOP_IPCORE";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMSSV 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MSSV", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MSSV"] = value;
		}
	}

	public bool IsMSSVNull() 
	{
		return pm_objDR.IsNull("MSSV");
	}

	public void SetMSSVNull() {
		pm_objDR["MSSV"] = System.Convert.DBNull;
	}

	public string strHO_VA_TEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HO_VA_TEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HO_VA_TEN"] = value;
		}
	}

	public bool IsHO_VA_TENNull() 
	{
		return pm_objDR.IsNull("HO_VA_TEN");
	}

	public void SetHO_VA_TENNull() {
		pm_objDR["HO_VA_TEN"] = System.Convert.DBNull;
	}

	public DateTime datBIRTH_DAY
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "BIRTH_DAY", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["BIRTH_DAY"] = value;
		}
	}

	public bool IsBIRTH_DAYNull()
	{
		return pm_objDR.IsNull("BIRTH_DAY");
	}

	public void SetBIRTH_DAYNull()
	{
		pm_objDR["BIRTH_DAY"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_LOP_IPCORE() 
	{
		pm_objDS = new DS_DM_LOP_IPCORE();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_LOP_IPCORE(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_LOP_IPCORE(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_LOP_IPCORE();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
}
}
