///************************************************
/// Generated by: tund
/// Date: 09/03/2009 08:20:19
/// Goal: Create User Service Class for TEST
///************************************************
/// <summary>
/// Create User Service Class for TEST
/// </summary>

namespace BKITrainingUS
{
using BKITrainingDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
    using System;


public class US_TEST : US_Object
{
	private const string c_TableName = "TEST";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strNAME 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NAME", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NAME"] = value;
		}
	}

	public bool IsNAMENull() 
	{
		return pm_objDR.IsNull("NAME");
	}

	public void SetNAMENull() {
		pm_objDR["NAME"] = System.Convert.DBNull;
	}

	public decimal dcAGES 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "AGES", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["AGES"] = value;
		}
	}

	public bool IsAGESNull()	{
		return pm_objDR.IsNull("AGES");
	}

	public void SetAGESNull() {
		pm_objDR["AGES"] = System.Convert.DBNull;
	}

	public DateTime datBIRDDAY
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "BIRDDAY", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["BIRDDAY"] = value;
		}
	}

	public bool IsBIRDDAYNull()
	{
		return pm_objDR.IsNull("BIRDDAY");
	}

	public void SetBIRDDAYNull()
	{
		pm_objDR["BIRDDAY"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_TEST() 
	{
		pm_objDS = new DS_TEST();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_TEST(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_TEST(decimal i_dbID) 
	{
		pm_objDS = new DS_TEST();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
}
}
