//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace AuctionDS {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DS_KET_QUA_TONG_HOP : DataSet {
        
        private KET_QUA_TONG_HOPDataTable tableKET_QUA_TONG_HOP;
        
        public DS_KET_QUA_TONG_HOP() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DS_KET_QUA_TONG_HOP(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["KET_QUA_TONG_HOP"] != null)) {
                    this.Tables.Add(new KET_QUA_TONG_HOPDataTable(ds.Tables["KET_QUA_TONG_HOP"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public KET_QUA_TONG_HOPDataTable KET_QUA_TONG_HOP {
            get {
                return this.tableKET_QUA_TONG_HOP;
            }
        }
        
        public override DataSet Clone() {
            DS_KET_QUA_TONG_HOP cln = ((DS_KET_QUA_TONG_HOP)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["KET_QUA_TONG_HOP"] != null)) {
                this.Tables.Add(new KET_QUA_TONG_HOPDataTable(ds.Tables["KET_QUA_TONG_HOP"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableKET_QUA_TONG_HOP = ((KET_QUA_TONG_HOPDataTable)(this.Tables["KET_QUA_TONG_HOP"]));
            if ((this.tableKET_QUA_TONG_HOP != null)) {
                this.tableKET_QUA_TONG_HOP.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DS_KET_QUA_TONG_HOP";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_KET_QUA_TONG_HOP.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableKET_QUA_TONG_HOP = new KET_QUA_TONG_HOPDataTable();
            this.Tables.Add(this.tableKET_QUA_TONG_HOP);
        }
        
        private bool ShouldSerializeKET_QUA_TONG_HOP() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void KET_QUA_TONG_HOPRowChangeEventHandler(object sender, KET_QUA_TONG_HOPRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class KET_QUA_TONG_HOPDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnDOT_DAU_GIA;
            
            private DataColumn columnNGAY_DAU_GIA;
            
            private DataColumn columnTONG_SO_CO_PHAN_CHAO_BAN;
            
            private DataColumn columnTONG_SO_NHA_DAU_TU_DANG_KY;
            
            private DataColumn columnTONG_SO_CO_PHAN_DANG_KY;
            
            private DataColumn columnTONG_SO_NHA_DAU_TU_HOP_LE;
            
            private DataColumn columnTONG_SO_NHA_DAU_TU_THAM_GIA;
            
            private DataColumn columnTONG_SO_NHA_DAU_TU_TRUNG_THAU;
            
            private DataColumn columnTONG_SO_CO_PHAN_DAT_MUA;
            
            private DataColumn columnTONG_SO_CO_PHAN_BAN_DUOC;
            
            private DataColumn columnTONG_SO_CO_PHAN_CHUA_BAN_DUOC;
            
            private DataColumn columnGIA_TRUNG_THAU_CAO_NHAT;
            
            private DataColumn columnGIA_TRUNG_THAU_THAP_NHAT;
            
            private DataColumn columnGIA_TRUNG_THAU_TRUNG_BINH;
            
            private DataColumn columnTONG_GIA_TRI_DAU_GIA;
            
            private DataColumn columnTOM_TAT_THEO_NHOM;
            
            private DataColumn columnSO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUA;
            
            private DataColumn columnMENH_GIA_CO_PHAN;
            
            private DataColumn columnGIA_KHOI_DIEM;
            
            private DataColumn columnTONG_NHA_DAU_TU_PHAP_NHAN;
            
            private DataColumn columnTONG_NHA_DAU_TU_CA_NHAN;
            
            private DataColumn columnKHOI_LUONG_DAT_CAO_NHAT;
            
            private DataColumn columnKHOI_LUONG_DAT_THAP_NHAT;
            
            private DataColumn columnGIA_DAT_CAO_NHAT;
            
            private DataColumn columnGIA_DAT_THAP_NHAT;
            
            private DataColumn columnSO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAI;
            
            internal KET_QUA_TONG_HOPDataTable() : 
                    base("KET_QUA_TONG_HOP") {
                this.InitClass();
            }
            
            internal KET_QUA_TONG_HOPDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn DOT_DAU_GIAColumn {
                get {
                    return this.columnDOT_DAU_GIA;
                }
            }
            
            internal DataColumn NGAY_DAU_GIAColumn {
                get {
                    return this.columnNGAY_DAU_GIA;
                }
            }
            
            internal DataColumn TONG_SO_CO_PHAN_CHAO_BANColumn {
                get {
                    return this.columnTONG_SO_CO_PHAN_CHAO_BAN;
                }
            }
            
            internal DataColumn TONG_SO_NHA_DAU_TU_DANG_KYColumn {
                get {
                    return this.columnTONG_SO_NHA_DAU_TU_DANG_KY;
                }
            }
            
            internal DataColumn TONG_SO_CO_PHAN_DANG_KYColumn {
                get {
                    return this.columnTONG_SO_CO_PHAN_DANG_KY;
                }
            }
            
            internal DataColumn TONG_SO_NHA_DAU_TU_HOP_LEColumn {
                get {
                    return this.columnTONG_SO_NHA_DAU_TU_HOP_LE;
                }
            }
            
            internal DataColumn TONG_SO_NHA_DAU_TU_THAM_GIAColumn {
                get {
                    return this.columnTONG_SO_NHA_DAU_TU_THAM_GIA;
                }
            }
            
            internal DataColumn TONG_SO_NHA_DAU_TU_TRUNG_THAUColumn {
                get {
                    return this.columnTONG_SO_NHA_DAU_TU_TRUNG_THAU;
                }
            }
            
            internal DataColumn TONG_SO_CO_PHAN_DAT_MUAColumn {
                get {
                    return this.columnTONG_SO_CO_PHAN_DAT_MUA;
                }
            }
            
            internal DataColumn TONG_SO_CO_PHAN_BAN_DUOCColumn {
                get {
                    return this.columnTONG_SO_CO_PHAN_BAN_DUOC;
                }
            }
            
            internal DataColumn TONG_SO_CO_PHAN_CHUA_BAN_DUOCColumn {
                get {
                    return this.columnTONG_SO_CO_PHAN_CHUA_BAN_DUOC;
                }
            }
            
            internal DataColumn GIA_TRUNG_THAU_CAO_NHATColumn {
                get {
                    return this.columnGIA_TRUNG_THAU_CAO_NHAT;
                }
            }
            
            internal DataColumn GIA_TRUNG_THAU_THAP_NHATColumn {
                get {
                    return this.columnGIA_TRUNG_THAU_THAP_NHAT;
                }
            }
            
            internal DataColumn GIA_TRUNG_THAU_TRUNG_BINHColumn {
                get {
                    return this.columnGIA_TRUNG_THAU_TRUNG_BINH;
                }
            }
            
            internal DataColumn TONG_GIA_TRI_DAU_GIAColumn {
                get {
                    return this.columnTONG_GIA_TRI_DAU_GIA;
                }
            }
            
            internal DataColumn TOM_TAT_THEO_NHOMColumn {
                get {
                    return this.columnTOM_TAT_THEO_NHOM;
                }
            }
            
            internal DataColumn SO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUAColumn {
                get {
                    return this.columnSO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUA;
                }
            }
            
            internal DataColumn MENH_GIA_CO_PHANColumn {
                get {
                    return this.columnMENH_GIA_CO_PHAN;
                }
            }
            
            internal DataColumn GIA_KHOI_DIEMColumn {
                get {
                    return this.columnGIA_KHOI_DIEM;
                }
            }
            
            internal DataColumn TONG_NHA_DAU_TU_PHAP_NHANColumn {
                get {
                    return this.columnTONG_NHA_DAU_TU_PHAP_NHAN;
                }
            }
            
            internal DataColumn TONG_NHA_DAU_TU_CA_NHANColumn {
                get {
                    return this.columnTONG_NHA_DAU_TU_CA_NHAN;
                }
            }
            
            internal DataColumn KHOI_LUONG_DAT_CAO_NHATColumn {
                get {
                    return this.columnKHOI_LUONG_DAT_CAO_NHAT;
                }
            }
            
            internal DataColumn KHOI_LUONG_DAT_THAP_NHATColumn {
                get {
                    return this.columnKHOI_LUONG_DAT_THAP_NHAT;
                }
            }
            
            internal DataColumn GIA_DAT_CAO_NHATColumn {
                get {
                    return this.columnGIA_DAT_CAO_NHAT;
                }
            }
            
            internal DataColumn GIA_DAT_THAP_NHATColumn {
                get {
                    return this.columnGIA_DAT_THAP_NHAT;
                }
            }
            
            internal DataColumn SO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAIColumn {
                get {
                    return this.columnSO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAI;
                }
            }
            
            public KET_QUA_TONG_HOPRow this[int index] {
                get {
                    return ((KET_QUA_TONG_HOPRow)(this.Rows[index]));
                }
            }
            
            public event KET_QUA_TONG_HOPRowChangeEventHandler KET_QUA_TONG_HOPRowChanged;
            
            public event KET_QUA_TONG_HOPRowChangeEventHandler KET_QUA_TONG_HOPRowChanging;
            
            public event KET_QUA_TONG_HOPRowChangeEventHandler KET_QUA_TONG_HOPRowDeleted;
            
            public event KET_QUA_TONG_HOPRowChangeEventHandler KET_QUA_TONG_HOPRowDeleting;
            
            public void AddKET_QUA_TONG_HOPRow(KET_QUA_TONG_HOPRow row) {
                this.Rows.Add(row);
            }
            
            public KET_QUA_TONG_HOPRow AddKET_QUA_TONG_HOPRow(
                        string DOT_DAU_GIA, 
                        System.DateTime NGAY_DAU_GIA, 
                        System.Decimal TONG_SO_CO_PHAN_CHAO_BAN, 
                        System.Decimal TONG_SO_NHA_DAU_TU_DANG_KY, 
                        System.Decimal TONG_SO_CO_PHAN_DANG_KY, 
                        System.Decimal TONG_SO_NHA_DAU_TU_HOP_LE, 
                        System.Decimal TONG_SO_NHA_DAU_TU_THAM_GIA, 
                        System.Decimal TONG_SO_NHA_DAU_TU_TRUNG_THAU, 
                        System.Decimal TONG_SO_CO_PHAN_DAT_MUA, 
                        System.Decimal TONG_SO_CO_PHAN_BAN_DUOC, 
                        System.Decimal TONG_SO_CO_PHAN_CHUA_BAN_DUOC, 
                        System.Decimal GIA_TRUNG_THAU_CAO_NHAT, 
                        System.Decimal GIA_TRUNG_THAU_THAP_NHAT, 
                        System.Decimal GIA_TRUNG_THAU_TRUNG_BINH, 
                        System.Decimal TONG_GIA_TRI_DAU_GIA, 
                        string TOM_TAT_THEO_NHOM, 
                        System.Decimal SO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUA, 
                        System.Decimal MENH_GIA_CO_PHAN, 
                        System.Decimal GIA_KHOI_DIEM, 
                        System.Decimal TONG_NHA_DAU_TU_PHAP_NHAN, 
                        System.Decimal TONG_NHA_DAU_TU_CA_NHAN, 
                        System.Decimal KHOI_LUONG_DAT_CAO_NHAT, 
                        System.Decimal KHOI_LUONG_DAT_THAP_NHAT, 
                        System.Decimal GIA_DAT_CAO_NHAT, 
                        System.Decimal GIA_DAT_THAP_NHAT, 
                        System.Decimal SO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAI) {
                KET_QUA_TONG_HOPRow rowKET_QUA_TONG_HOPRow = ((KET_QUA_TONG_HOPRow)(this.NewRow()));
                rowKET_QUA_TONG_HOPRow.ItemArray = new object[] {
                        DOT_DAU_GIA,
                        NGAY_DAU_GIA,
                        TONG_SO_CO_PHAN_CHAO_BAN,
                        TONG_SO_NHA_DAU_TU_DANG_KY,
                        TONG_SO_CO_PHAN_DANG_KY,
                        TONG_SO_NHA_DAU_TU_HOP_LE,
                        TONG_SO_NHA_DAU_TU_THAM_GIA,
                        TONG_SO_NHA_DAU_TU_TRUNG_THAU,
                        TONG_SO_CO_PHAN_DAT_MUA,
                        TONG_SO_CO_PHAN_BAN_DUOC,
                        TONG_SO_CO_PHAN_CHUA_BAN_DUOC,
                        GIA_TRUNG_THAU_CAO_NHAT,
                        GIA_TRUNG_THAU_THAP_NHAT,
                        GIA_TRUNG_THAU_TRUNG_BINH,
                        TONG_GIA_TRI_DAU_GIA,
                        TOM_TAT_THEO_NHOM,
                        SO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUA,
                        MENH_GIA_CO_PHAN,
                        GIA_KHOI_DIEM,
                        TONG_NHA_DAU_TU_PHAP_NHAN,
                        TONG_NHA_DAU_TU_CA_NHAN,
                        KHOI_LUONG_DAT_CAO_NHAT,
                        KHOI_LUONG_DAT_THAP_NHAT,
                        GIA_DAT_CAO_NHAT,
                        GIA_DAT_THAP_NHAT,
                        SO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAI};
                this.Rows.Add(rowKET_QUA_TONG_HOPRow);
                return rowKET_QUA_TONG_HOPRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                KET_QUA_TONG_HOPDataTable cln = ((KET_QUA_TONG_HOPDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new KET_QUA_TONG_HOPDataTable();
            }
            
            internal void InitVars() {
                this.columnDOT_DAU_GIA = this.Columns["DOT_DAU_GIA"];
                this.columnNGAY_DAU_GIA = this.Columns["NGAY_DAU_GIA"];
                this.columnTONG_SO_CO_PHAN_CHAO_BAN = this.Columns["TONG_SO_CO_PHAN_CHAO_BAN"];
                this.columnTONG_SO_NHA_DAU_TU_DANG_KY = this.Columns["TONG_SO_NHA_DAU_TU_DANG_KY"];
                this.columnTONG_SO_CO_PHAN_DANG_KY = this.Columns["TONG_SO_CO_PHAN_DANG_KY"];
                this.columnTONG_SO_NHA_DAU_TU_HOP_LE = this.Columns["TONG_SO_NHA_DAU_TU_HOP_LE"];
                this.columnTONG_SO_NHA_DAU_TU_THAM_GIA = this.Columns["TONG_SO_NHA_DAU_TU_THAM_GIA"];
                this.columnTONG_SO_NHA_DAU_TU_TRUNG_THAU = this.Columns["TONG_SO_NHA_DAU_TU_TRUNG_THAU"];
                this.columnTONG_SO_CO_PHAN_DAT_MUA = this.Columns["TONG_SO_CO_PHAN_DAT_MUA"];
                this.columnTONG_SO_CO_PHAN_BAN_DUOC = this.Columns["TONG_SO_CO_PHAN_BAN_DUOC"];
                this.columnTONG_SO_CO_PHAN_CHUA_BAN_DUOC = this.Columns["TONG_SO_CO_PHAN_CHUA_BAN_DUOC"];
                this.columnGIA_TRUNG_THAU_CAO_NHAT = this.Columns["GIA_TRUNG_THAU_CAO_NHAT"];
                this.columnGIA_TRUNG_THAU_THAP_NHAT = this.Columns["GIA_TRUNG_THAU_THAP_NHAT"];
                this.columnGIA_TRUNG_THAU_TRUNG_BINH = this.Columns["GIA_TRUNG_THAU_TRUNG_BINH"];
                this.columnTONG_GIA_TRI_DAU_GIA = this.Columns["TONG_GIA_TRI_DAU_GIA"];
                this.columnTOM_TAT_THEO_NHOM = this.Columns["TOM_TAT_THEO_NHOM"];
                this.columnSO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUA = this.Columns["SO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUA"];
                this.columnMENH_GIA_CO_PHAN = this.Columns["MENH_GIA_CO_PHAN"];
                this.columnGIA_KHOI_DIEM = this.Columns["GIA_KHOI_DIEM"];
                this.columnTONG_NHA_DAU_TU_PHAP_NHAN = this.Columns["TONG_NHA_DAU_TU_PHAP_NHAN"];
                this.columnTONG_NHA_DAU_TU_CA_NHAN = this.Columns["TONG_NHA_DAU_TU_CA_NHAN"];
                this.columnKHOI_LUONG_DAT_CAO_NHAT = this.Columns["KHOI_LUONG_DAT_CAO_NHAT"];
                this.columnKHOI_LUONG_DAT_THAP_NHAT = this.Columns["KHOI_LUONG_DAT_THAP_NHAT"];
                this.columnGIA_DAT_CAO_NHAT = this.Columns["GIA_DAT_CAO_NHAT"];
                this.columnGIA_DAT_THAP_NHAT = this.Columns["GIA_DAT_THAP_NHAT"];
                this.columnSO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAI = this.Columns["SO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAI"];
            }
            
            private void InitClass() {
                this.columnDOT_DAU_GIA = new DataColumn("DOT_DAU_GIA", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDOT_DAU_GIA);
                this.columnNGAY_DAU_GIA = new DataColumn("NGAY_DAU_GIA", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNGAY_DAU_GIA);
                this.columnTONG_SO_CO_PHAN_CHAO_BAN = new DataColumn("TONG_SO_CO_PHAN_CHAO_BAN", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_SO_CO_PHAN_CHAO_BAN);
                this.columnTONG_SO_NHA_DAU_TU_DANG_KY = new DataColumn("TONG_SO_NHA_DAU_TU_DANG_KY", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_SO_NHA_DAU_TU_DANG_KY);
                this.columnTONG_SO_CO_PHAN_DANG_KY = new DataColumn("TONG_SO_CO_PHAN_DANG_KY", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_SO_CO_PHAN_DANG_KY);
                this.columnTONG_SO_NHA_DAU_TU_HOP_LE = new DataColumn("TONG_SO_NHA_DAU_TU_HOP_LE", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_SO_NHA_DAU_TU_HOP_LE);
                this.columnTONG_SO_NHA_DAU_TU_THAM_GIA = new DataColumn("TONG_SO_NHA_DAU_TU_THAM_GIA", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_SO_NHA_DAU_TU_THAM_GIA);
                this.columnTONG_SO_NHA_DAU_TU_TRUNG_THAU = new DataColumn("TONG_SO_NHA_DAU_TU_TRUNG_THAU", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_SO_NHA_DAU_TU_TRUNG_THAU);
                this.columnTONG_SO_CO_PHAN_DAT_MUA = new DataColumn("TONG_SO_CO_PHAN_DAT_MUA", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_SO_CO_PHAN_DAT_MUA);
                this.columnTONG_SO_CO_PHAN_BAN_DUOC = new DataColumn("TONG_SO_CO_PHAN_BAN_DUOC", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_SO_CO_PHAN_BAN_DUOC);
                this.columnTONG_SO_CO_PHAN_CHUA_BAN_DUOC = new DataColumn("TONG_SO_CO_PHAN_CHUA_BAN_DUOC", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_SO_CO_PHAN_CHUA_BAN_DUOC);
                this.columnGIA_TRUNG_THAU_CAO_NHAT = new DataColumn("GIA_TRUNG_THAU_CAO_NHAT", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGIA_TRUNG_THAU_CAO_NHAT);
                this.columnGIA_TRUNG_THAU_THAP_NHAT = new DataColumn("GIA_TRUNG_THAU_THAP_NHAT", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGIA_TRUNG_THAU_THAP_NHAT);
                this.columnGIA_TRUNG_THAU_TRUNG_BINH = new DataColumn("GIA_TRUNG_THAU_TRUNG_BINH", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGIA_TRUNG_THAU_TRUNG_BINH);
                this.columnTONG_GIA_TRI_DAU_GIA = new DataColumn("TONG_GIA_TRI_DAU_GIA", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_GIA_TRI_DAU_GIA);
                this.columnTOM_TAT_THEO_NHOM = new DataColumn("TOM_TAT_THEO_NHOM", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTOM_TAT_THEO_NHOM);
                this.columnSO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUA = new DataColumn("SO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUA", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUA);
                this.columnMENH_GIA_CO_PHAN = new DataColumn("MENH_GIA_CO_PHAN", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMENH_GIA_CO_PHAN);
                this.columnGIA_KHOI_DIEM = new DataColumn("GIA_KHOI_DIEM", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGIA_KHOI_DIEM);
                this.columnTONG_NHA_DAU_TU_PHAP_NHAN = new DataColumn("TONG_NHA_DAU_TU_PHAP_NHAN", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_NHA_DAU_TU_PHAP_NHAN);
                this.columnTONG_NHA_DAU_TU_CA_NHAN = new DataColumn("TONG_NHA_DAU_TU_CA_NHAN", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTONG_NHA_DAU_TU_CA_NHAN);
                this.columnKHOI_LUONG_DAT_CAO_NHAT = new DataColumn("KHOI_LUONG_DAT_CAO_NHAT", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnKHOI_LUONG_DAT_CAO_NHAT);
                this.columnKHOI_LUONG_DAT_THAP_NHAT = new DataColumn("KHOI_LUONG_DAT_THAP_NHAT", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnKHOI_LUONG_DAT_THAP_NHAT);
                this.columnGIA_DAT_CAO_NHAT = new DataColumn("GIA_DAT_CAO_NHAT", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGIA_DAT_CAO_NHAT);
                this.columnGIA_DAT_THAP_NHAT = new DataColumn("GIA_DAT_THAP_NHAT", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGIA_DAT_THAP_NHAT);
                this.columnSO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAI = new DataColumn("SO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAI", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAI);
            }
            
            public KET_QUA_TONG_HOPRow NewKET_QUA_TONG_HOPRow() {
                return ((KET_QUA_TONG_HOPRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new KET_QUA_TONG_HOPRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(KET_QUA_TONG_HOPRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.KET_QUA_TONG_HOPRowChanged != null)) {
                    this.KET_QUA_TONG_HOPRowChanged(this, new KET_QUA_TONG_HOPRowChangeEvent(((KET_QUA_TONG_HOPRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.KET_QUA_TONG_HOPRowChanging != null)) {
                    this.KET_QUA_TONG_HOPRowChanging(this, new KET_QUA_TONG_HOPRowChangeEvent(((KET_QUA_TONG_HOPRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.KET_QUA_TONG_HOPRowDeleted != null)) {
                    this.KET_QUA_TONG_HOPRowDeleted(this, new KET_QUA_TONG_HOPRowChangeEvent(((KET_QUA_TONG_HOPRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.KET_QUA_TONG_HOPRowDeleting != null)) {
                    this.KET_QUA_TONG_HOPRowDeleting(this, new KET_QUA_TONG_HOPRowChangeEvent(((KET_QUA_TONG_HOPRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveKET_QUA_TONG_HOPRow(KET_QUA_TONG_HOPRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class KET_QUA_TONG_HOPRow : DataRow {
            
            private KET_QUA_TONG_HOPDataTable tableKET_QUA_TONG_HOP;
            
            internal KET_QUA_TONG_HOPRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableKET_QUA_TONG_HOP = ((KET_QUA_TONG_HOPDataTable)(this.Table));
            }
            
            public string DOT_DAU_GIA {
                get {
                    try {
                        return ((string)(this[this.tableKET_QUA_TONG_HOP.DOT_DAU_GIAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.DOT_DAU_GIAColumn] = value;
                }
            }
            
            public System.DateTime NGAY_DAU_GIA {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableKET_QUA_TONG_HOP.NGAY_DAU_GIAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.NGAY_DAU_GIAColumn] = value;
                }
            }
            
            public System.Decimal TONG_SO_CO_PHAN_CHAO_BAN {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_CHAO_BANColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_CHAO_BANColumn] = value;
                }
            }
            
            public System.Decimal TONG_SO_NHA_DAU_TU_DANG_KY {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_DANG_KYColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_DANG_KYColumn] = value;
                }
            }
            
            public System.Decimal TONG_SO_CO_PHAN_DANG_KY {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_DANG_KYColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_DANG_KYColumn] = value;
                }
            }
            
            public System.Decimal TONG_SO_NHA_DAU_TU_HOP_LE {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_HOP_LEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_HOP_LEColumn] = value;
                }
            }
            
            public System.Decimal TONG_SO_NHA_DAU_TU_THAM_GIA {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_THAM_GIAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_THAM_GIAColumn] = value;
                }
            }
            
            public System.Decimal TONG_SO_NHA_DAU_TU_TRUNG_THAU {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_TRUNG_THAUColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_TRUNG_THAUColumn] = value;
                }
            }
            
            public System.Decimal TONG_SO_CO_PHAN_DAT_MUA {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_DAT_MUAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_DAT_MUAColumn] = value;
                }
            }
            
            public System.Decimal TONG_SO_CO_PHAN_BAN_DUOC {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_BAN_DUOCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_BAN_DUOCColumn] = value;
                }
            }
            
            public System.Decimal TONG_SO_CO_PHAN_CHUA_BAN_DUOC {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_CHUA_BAN_DUOCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_CHUA_BAN_DUOCColumn] = value;
                }
            }
            
            public System.Decimal GIA_TRUNG_THAU_CAO_NHAT {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_CAO_NHATColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_CAO_NHATColumn] = value;
                }
            }
            
            public System.Decimal GIA_TRUNG_THAU_THAP_NHAT {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_THAP_NHATColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_THAP_NHATColumn] = value;
                }
            }
            
            public System.Decimal GIA_TRUNG_THAU_TRUNG_BINH {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_TRUNG_BINHColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_TRUNG_BINHColumn] = value;
                }
            }
            
            public System.Decimal TONG_GIA_TRI_DAU_GIA {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_GIA_TRI_DAU_GIAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_GIA_TRI_DAU_GIAColumn] = value;
                }
            }
            
            public string TOM_TAT_THEO_NHOM {
                get {
                    try {
                        return ((string)(this[this.tableKET_QUA_TONG_HOP.TOM_TAT_THEO_NHOMColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TOM_TAT_THEO_NHOMColumn] = value;
                }
            }
            
            public System.Decimal SO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUA {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.SO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.SO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUAColumn] = value;
                }
            }
            
            public System.Decimal MENH_GIA_CO_PHAN {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.MENH_GIA_CO_PHANColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.MENH_GIA_CO_PHANColumn] = value;
                }
            }
            
            public System.Decimal GIA_KHOI_DIEM {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.GIA_KHOI_DIEMColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.GIA_KHOI_DIEMColumn] = value;
                }
            }
            
            public System.Decimal TONG_NHA_DAU_TU_PHAP_NHAN {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_NHA_DAU_TU_PHAP_NHANColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_NHA_DAU_TU_PHAP_NHANColumn] = value;
                }
            }
            
            public System.Decimal TONG_NHA_DAU_TU_CA_NHAN {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.TONG_NHA_DAU_TU_CA_NHANColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.TONG_NHA_DAU_TU_CA_NHANColumn] = value;
                }
            }
            
            public System.Decimal KHOI_LUONG_DAT_CAO_NHAT {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.KHOI_LUONG_DAT_CAO_NHATColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.KHOI_LUONG_DAT_CAO_NHATColumn] = value;
                }
            }
            
            public System.Decimal KHOI_LUONG_DAT_THAP_NHAT {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.KHOI_LUONG_DAT_THAP_NHATColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.KHOI_LUONG_DAT_THAP_NHATColumn] = value;
                }
            }
            
            public System.Decimal GIA_DAT_CAO_NHAT {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.GIA_DAT_CAO_NHATColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.GIA_DAT_CAO_NHATColumn] = value;
                }
            }
            
            public System.Decimal GIA_DAT_THAP_NHAT {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.GIA_DAT_THAP_NHATColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.GIA_DAT_THAP_NHATColumn] = value;
                }
            }
            
            public System.Decimal SO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAI {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableKET_QUA_TONG_HOP.SO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAIColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableKET_QUA_TONG_HOP.SO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAIColumn] = value;
                }
            }
            
            public bool IsDOT_DAU_GIANull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.DOT_DAU_GIAColumn);
            }
            
            public void SetDOT_DAU_GIANull() {
                this[this.tableKET_QUA_TONG_HOP.DOT_DAU_GIAColumn] = System.Convert.DBNull;
            }
            
            public bool IsNGAY_DAU_GIANull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.NGAY_DAU_GIAColumn);
            }
            
            public void SetNGAY_DAU_GIANull() {
                this[this.tableKET_QUA_TONG_HOP.NGAY_DAU_GIAColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_SO_CO_PHAN_CHAO_BANNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_CHAO_BANColumn);
            }
            
            public void SetTONG_SO_CO_PHAN_CHAO_BANNull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_CHAO_BANColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_SO_NHA_DAU_TU_DANG_KYNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_DANG_KYColumn);
            }
            
            public void SetTONG_SO_NHA_DAU_TU_DANG_KYNull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_DANG_KYColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_SO_CO_PHAN_DANG_KYNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_DANG_KYColumn);
            }
            
            public void SetTONG_SO_CO_PHAN_DANG_KYNull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_DANG_KYColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_SO_NHA_DAU_TU_HOP_LENull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_HOP_LEColumn);
            }
            
            public void SetTONG_SO_NHA_DAU_TU_HOP_LENull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_HOP_LEColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_SO_NHA_DAU_TU_THAM_GIANull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_THAM_GIAColumn);
            }
            
            public void SetTONG_SO_NHA_DAU_TU_THAM_GIANull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_THAM_GIAColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_SO_NHA_DAU_TU_TRUNG_THAUNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_TRUNG_THAUColumn);
            }
            
            public void SetTONG_SO_NHA_DAU_TU_TRUNG_THAUNull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_SO_NHA_DAU_TU_TRUNG_THAUColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_SO_CO_PHAN_DAT_MUANull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_DAT_MUAColumn);
            }
            
            public void SetTONG_SO_CO_PHAN_DAT_MUANull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_DAT_MUAColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_SO_CO_PHAN_BAN_DUOCNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_BAN_DUOCColumn);
            }
            
            public void SetTONG_SO_CO_PHAN_BAN_DUOCNull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_BAN_DUOCColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_SO_CO_PHAN_CHUA_BAN_DUOCNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_CHUA_BAN_DUOCColumn);
            }
            
            public void SetTONG_SO_CO_PHAN_CHUA_BAN_DUOCNull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_SO_CO_PHAN_CHUA_BAN_DUOCColumn] = System.Convert.DBNull;
            }
            
            public bool IsGIA_TRUNG_THAU_CAO_NHATNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_CAO_NHATColumn);
            }
            
            public void SetGIA_TRUNG_THAU_CAO_NHATNull() {
                this[this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_CAO_NHATColumn] = System.Convert.DBNull;
            }
            
            public bool IsGIA_TRUNG_THAU_THAP_NHATNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_THAP_NHATColumn);
            }
            
            public void SetGIA_TRUNG_THAU_THAP_NHATNull() {
                this[this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_THAP_NHATColumn] = System.Convert.DBNull;
            }
            
            public bool IsGIA_TRUNG_THAU_TRUNG_BINHNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_TRUNG_BINHColumn);
            }
            
            public void SetGIA_TRUNG_THAU_TRUNG_BINHNull() {
                this[this.tableKET_QUA_TONG_HOP.GIA_TRUNG_THAU_TRUNG_BINHColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_GIA_TRI_DAU_GIANull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_GIA_TRI_DAU_GIAColumn);
            }
            
            public void SetTONG_GIA_TRI_DAU_GIANull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_GIA_TRI_DAU_GIAColumn] = System.Convert.DBNull;
            }
            
            public bool IsTOM_TAT_THEO_NHOMNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TOM_TAT_THEO_NHOMColumn);
            }
            
            public void SetTOM_TAT_THEO_NHOMNull() {
                this[this.tableKET_QUA_TONG_HOP.TOM_TAT_THEO_NHOMColumn] = System.Convert.DBNull;
            }
            
            public bool IsSO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUANull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.SO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUAColumn);
            }
            
            public void SetSO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUANull() {
                this[this.tableKET_QUA_TONG_HOP.SO_LUONG_CO_PHAN_NGUOI_NUOC_NGOAI_DUOC_MUAColumn] = System.Convert.DBNull;
            }
            
            public bool IsMENH_GIA_CO_PHANNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.MENH_GIA_CO_PHANColumn);
            }
            
            public void SetMENH_GIA_CO_PHANNull() {
                this[this.tableKET_QUA_TONG_HOP.MENH_GIA_CO_PHANColumn] = System.Convert.DBNull;
            }
            
            public bool IsGIA_KHOI_DIEMNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.GIA_KHOI_DIEMColumn);
            }
            
            public void SetGIA_KHOI_DIEMNull() {
                this[this.tableKET_QUA_TONG_HOP.GIA_KHOI_DIEMColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_NHA_DAU_TU_PHAP_NHANNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_NHA_DAU_TU_PHAP_NHANColumn);
            }
            
            public void SetTONG_NHA_DAU_TU_PHAP_NHANNull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_NHA_DAU_TU_PHAP_NHANColumn] = System.Convert.DBNull;
            }
            
            public bool IsTONG_NHA_DAU_TU_CA_NHANNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.TONG_NHA_DAU_TU_CA_NHANColumn);
            }
            
            public void SetTONG_NHA_DAU_TU_CA_NHANNull() {
                this[this.tableKET_QUA_TONG_HOP.TONG_NHA_DAU_TU_CA_NHANColumn] = System.Convert.DBNull;
            }
            
            public bool IsKHOI_LUONG_DAT_CAO_NHATNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.KHOI_LUONG_DAT_CAO_NHATColumn);
            }
            
            public void SetKHOI_LUONG_DAT_CAO_NHATNull() {
                this[this.tableKET_QUA_TONG_HOP.KHOI_LUONG_DAT_CAO_NHATColumn] = System.Convert.DBNull;
            }
            
            public bool IsKHOI_LUONG_DAT_THAP_NHATNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.KHOI_LUONG_DAT_THAP_NHATColumn);
            }
            
            public void SetKHOI_LUONG_DAT_THAP_NHATNull() {
                this[this.tableKET_QUA_TONG_HOP.KHOI_LUONG_DAT_THAP_NHATColumn] = System.Convert.DBNull;
            }
            
            public bool IsGIA_DAT_CAO_NHATNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.GIA_DAT_CAO_NHATColumn);
            }
            
            public void SetGIA_DAT_CAO_NHATNull() {
                this[this.tableKET_QUA_TONG_HOP.GIA_DAT_CAO_NHATColumn] = System.Convert.DBNull;
            }
            
            public bool IsGIA_DAT_THAP_NHATNull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.GIA_DAT_THAP_NHATColumn);
            }
            
            public void SetGIA_DAT_THAP_NHATNull() {
                this[this.tableKET_QUA_TONG_HOP.GIA_DAT_THAP_NHATColumn] = System.Convert.DBNull;
            }
            
            public bool IsSO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAINull() {
                return this.IsNull(this.tableKET_QUA_TONG_HOP.SO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAIColumn);
            }
            
            public void SetSO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAINull() {
                this[this.tableKET_QUA_TONG_HOP.SO_CO_PHAN_TRUNG_CUA_NGUOI_NUOC_NGOAIColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class KET_QUA_TONG_HOPRowChangeEvent : EventArgs {
            
            private KET_QUA_TONG_HOPRow eventRow;
            
            private DataRowAction eventAction;
            
            public KET_QUA_TONG_HOPRowChangeEvent(KET_QUA_TONG_HOPRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public KET_QUA_TONG_HOPRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
