//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace AuctionDS {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DS_SO_DONG_4_PHIEU_DANG_KY : DataSet {
        
        private SO_DONG_4_PHIEU_DANG_KYDataTable tableSO_DONG_4_PHIEU_DANG_KY;
        
        public DS_SO_DONG_4_PHIEU_DANG_KY() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DS_SO_DONG_4_PHIEU_DANG_KY(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["SO_DONG_4_PHIEU_DANG_KY"] != null)) {
                    this.Tables.Add(new SO_DONG_4_PHIEU_DANG_KYDataTable(ds.Tables["SO_DONG_4_PHIEU_DANG_KY"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SO_DONG_4_PHIEU_DANG_KYDataTable SO_DONG_4_PHIEU_DANG_KY {
            get {
                return this.tableSO_DONG_4_PHIEU_DANG_KY;
            }
        }
        
        public override DataSet Clone() {
            DS_SO_DONG_4_PHIEU_DANG_KY cln = ((DS_SO_DONG_4_PHIEU_DANG_KY)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["SO_DONG_4_PHIEU_DANG_KY"] != null)) {
                this.Tables.Add(new SO_DONG_4_PHIEU_DANG_KYDataTable(ds.Tables["SO_DONG_4_PHIEU_DANG_KY"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableSO_DONG_4_PHIEU_DANG_KY = ((SO_DONG_4_PHIEU_DANG_KYDataTable)(this.Tables["SO_DONG_4_PHIEU_DANG_KY"]));
            if ((this.tableSO_DONG_4_PHIEU_DANG_KY != null)) {
                this.tableSO_DONG_4_PHIEU_DANG_KY.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DS_SO_DONG_4_PHIEU_DANG_KY";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_SO_DONG_4_PHIEU_DANG_KY.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableSO_DONG_4_PHIEU_DANG_KY = new SO_DONG_4_PHIEU_DANG_KYDataTable();
            this.Tables.Add(this.tableSO_DONG_4_PHIEU_DANG_KY);
        }
        
        private bool ShouldSerializeSO_DONG_4_PHIEU_DANG_KY() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void SO_DONG_4_PHIEU_DANG_KYRowChangeEventHandler(object sender, SO_DONG_4_PHIEU_DANG_KYRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SO_DONG_4_PHIEU_DANG_KYDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnID_AUCTION;
            
            private DataColumn columnSTT;
            
            internal SO_DONG_4_PHIEU_DANG_KYDataTable() : 
                    base("SO_DONG_4_PHIEU_DANG_KY") {
                this.InitClass();
            }
            
            internal SO_DONG_4_PHIEU_DANG_KYDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn ID_AUCTIONColumn {
                get {
                    return this.columnID_AUCTION;
                }
            }
            
            internal DataColumn STTColumn {
                get {
                    return this.columnSTT;
                }
            }
            
            public SO_DONG_4_PHIEU_DANG_KYRow this[int index] {
                get {
                    return ((SO_DONG_4_PHIEU_DANG_KYRow)(this.Rows[index]));
                }
            }
            
            public event SO_DONG_4_PHIEU_DANG_KYRowChangeEventHandler SO_DONG_4_PHIEU_DANG_KYRowChanged;
            
            public event SO_DONG_4_PHIEU_DANG_KYRowChangeEventHandler SO_DONG_4_PHIEU_DANG_KYRowChanging;
            
            public event SO_DONG_4_PHIEU_DANG_KYRowChangeEventHandler SO_DONG_4_PHIEU_DANG_KYRowDeleted;
            
            public event SO_DONG_4_PHIEU_DANG_KYRowChangeEventHandler SO_DONG_4_PHIEU_DANG_KYRowDeleting;
            
            public void AddSO_DONG_4_PHIEU_DANG_KYRow(SO_DONG_4_PHIEU_DANG_KYRow row) {
                this.Rows.Add(row);
            }
            
            public SO_DONG_4_PHIEU_DANG_KYRow AddSO_DONG_4_PHIEU_DANG_KYRow(System.Decimal ID_AUCTION, System.Decimal STT) {
                SO_DONG_4_PHIEU_DANG_KYRow rowSO_DONG_4_PHIEU_DANG_KYRow = ((SO_DONG_4_PHIEU_DANG_KYRow)(this.NewRow()));
                rowSO_DONG_4_PHIEU_DANG_KYRow.ItemArray = new object[] {
                        ID_AUCTION,
                        STT};
                this.Rows.Add(rowSO_DONG_4_PHIEU_DANG_KYRow);
                return rowSO_DONG_4_PHIEU_DANG_KYRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                SO_DONG_4_PHIEU_DANG_KYDataTable cln = ((SO_DONG_4_PHIEU_DANG_KYDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new SO_DONG_4_PHIEU_DANG_KYDataTable();
            }
            
            internal void InitVars() {
                this.columnID_AUCTION = this.Columns["ID_AUCTION"];
                this.columnSTT = this.Columns["STT"];
            }
            
            private void InitClass() {
                this.columnID_AUCTION = new DataColumn("ID_AUCTION", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnID_AUCTION);
                this.columnSTT = new DataColumn("STT", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSTT);
            }
            
            public SO_DONG_4_PHIEU_DANG_KYRow NewSO_DONG_4_PHIEU_DANG_KYRow() {
                return ((SO_DONG_4_PHIEU_DANG_KYRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new SO_DONG_4_PHIEU_DANG_KYRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(SO_DONG_4_PHIEU_DANG_KYRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SO_DONG_4_PHIEU_DANG_KYRowChanged != null)) {
                    this.SO_DONG_4_PHIEU_DANG_KYRowChanged(this, new SO_DONG_4_PHIEU_DANG_KYRowChangeEvent(((SO_DONG_4_PHIEU_DANG_KYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SO_DONG_4_PHIEU_DANG_KYRowChanging != null)) {
                    this.SO_DONG_4_PHIEU_DANG_KYRowChanging(this, new SO_DONG_4_PHIEU_DANG_KYRowChangeEvent(((SO_DONG_4_PHIEU_DANG_KYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SO_DONG_4_PHIEU_DANG_KYRowDeleted != null)) {
                    this.SO_DONG_4_PHIEU_DANG_KYRowDeleted(this, new SO_DONG_4_PHIEU_DANG_KYRowChangeEvent(((SO_DONG_4_PHIEU_DANG_KYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SO_DONG_4_PHIEU_DANG_KYRowDeleting != null)) {
                    this.SO_DONG_4_PHIEU_DANG_KYRowDeleting(this, new SO_DONG_4_PHIEU_DANG_KYRowChangeEvent(((SO_DONG_4_PHIEU_DANG_KYRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveSO_DONG_4_PHIEU_DANG_KYRow(SO_DONG_4_PHIEU_DANG_KYRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SO_DONG_4_PHIEU_DANG_KYRow : DataRow {
            
            private SO_DONG_4_PHIEU_DANG_KYDataTable tableSO_DONG_4_PHIEU_DANG_KY;
            
            internal SO_DONG_4_PHIEU_DANG_KYRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableSO_DONG_4_PHIEU_DANG_KY = ((SO_DONG_4_PHIEU_DANG_KYDataTable)(this.Table));
            }
            
            public System.Decimal ID_AUCTION {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableSO_DONG_4_PHIEU_DANG_KY.ID_AUCTIONColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSO_DONG_4_PHIEU_DANG_KY.ID_AUCTIONColumn] = value;
                }
            }
            
            public System.Decimal STT {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableSO_DONG_4_PHIEU_DANG_KY.STTColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSO_DONG_4_PHIEU_DANG_KY.STTColumn] = value;
                }
            }
            
            public bool IsID_AUCTIONNull() {
                return this.IsNull(this.tableSO_DONG_4_PHIEU_DANG_KY.ID_AUCTIONColumn);
            }
            
            public void SetID_AUCTIONNull() {
                this[this.tableSO_DONG_4_PHIEU_DANG_KY.ID_AUCTIONColumn] = System.Convert.DBNull;
            }
            
            public bool IsSTTNull() {
                return this.IsNull(this.tableSO_DONG_4_PHIEU_DANG_KY.STTColumn);
            }
            
            public void SetSTTNull() {
                this[this.tableSO_DONG_4_PHIEU_DANG_KY.STTColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SO_DONG_4_PHIEU_DANG_KYRowChangeEvent : EventArgs {
            
            private SO_DONG_4_PHIEU_DANG_KYRow eventRow;
            
            private DataRowAction eventAction;
            
            public SO_DONG_4_PHIEU_DANG_KYRowChangeEvent(SO_DONG_4_PHIEU_DANG_KYRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public SO_DONG_4_PHIEU_DANG_KYRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
