///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'BKINDEX_MEMBERS'
// Generated by LLBLGen v1.21.2003.712 Final on: Friday, April 27, 2012, 6:55:43 PM
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace AUCTION_IBSLLBL
{
	/// <summary>
	/// Purpose: Data Access class for the table 'BKINDEX_MEMBERS'.
	/// </summary>
	public class BKINDEX_MEMBERS : DBInteractionBase
	{
		#region Class Member Declarations
			private SqlDateTime		_bIRTH_DAY;
			private SqlDecimal		_lEVEL_MODE, _iD;
			private SqlString		_mEMBER_NAME, _gIOI_TINH_YN;
		#endregion


		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public BKINDEX_MEMBERS()
		{
			// Nothing for now.
		}


		/// <summary>
		/// Purpose: Insert method. This method will insert one new row into the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>MEMBER_NAME</LI>
		///		 <LI>BIRTH_DAY. May be SqlDateTime.Null</LI>
		///		 <LI>GIOI_TINH_YN</LI>
		///		 <LI>LEVEL_MODE</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ID</LI>
		/// </UL>
		/// </remarks>
		public override bool Insert()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_BKINDEX_MEMBERS_Insert]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@MEMBER_NAME", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _mEMBER_NAME));
				cmdToExecute.Parameters.Add(new SqlParameter("@BIRTH_DAY", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _bIRTH_DAY));
				cmdToExecute.Parameters.Add(new SqlParameter("@GIOI_TINH_YN", SqlDbType.NVarChar, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _gIOI_TINH_YN));
				cmdToExecute.Parameters.Add(new SqlParameter("@LEVEL_MODE", SqlDbType.Decimal, 5, ParameterDirection.Input, false, 4, 1, "", DataRowVersion.Proposed, _lEVEL_MODE));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID", SqlDbType.Decimal, 9, ParameterDirection.Output, false, 18, 1, "", DataRowVersion.Proposed, _iD));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				_iD = (Decimal)cmdToExecute.Parameters["@ID"].Value;
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("BKINDEX_MEMBERS::Insert::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Update method. This method will Update one existing row in the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID</LI>
		///		 <LI>MEMBER_NAME</LI>
		///		 <LI>BIRTH_DAY. May be SqlDateTime.Null</LI>
		///		 <LI>GIOI_TINH_YN</LI>
		///		 <LI>LEVEL_MODE</LI>
		/// </UL>
		/// </remarks>
		public override bool Update()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_BKINDEX_MEMBERS_Update]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD));
				cmdToExecute.Parameters.Add(new SqlParameter("@MEMBER_NAME", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _mEMBER_NAME));
				cmdToExecute.Parameters.Add(new SqlParameter("@BIRTH_DAY", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _bIRTH_DAY));
				cmdToExecute.Parameters.Add(new SqlParameter("@GIOI_TINH_YN", SqlDbType.NVarChar, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _gIOI_TINH_YN));
				cmdToExecute.Parameters.Add(new SqlParameter("@LEVEL_MODE", SqlDbType.Decimal, 5, ParameterDirection.Input, false, 4, 1, "", DataRowVersion.Proposed, _lEVEL_MODE));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("BKINDEX_MEMBERS::Update::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Delete method. This method will Delete one existing row in the database, based on the Primary Key.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID</LI>
		/// </UL>
		/// </remarks>
		public override bool Delete()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_BKINDEX_MEMBERS_Delete]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("BKINDEX_MEMBERS::Delete::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		#region Class Property Declarations
		public SqlDecimal ID
		{
			get
			{
				return _iD;
			}
			set
			{
				SqlDecimal iDTmp = (SqlDecimal)value;
				if(iDTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID", "ID can't be NULL");
				}
				_iD = value;
			}
		}


		public SqlString MEMBER_NAME
		{
			get
			{
				return _mEMBER_NAME;
			}
			set
			{
				SqlString mEMBER_NAMETmp = (SqlString)value;
				if(mEMBER_NAMETmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("MEMBER_NAME", "MEMBER_NAME can't be NULL");
				}
				_mEMBER_NAME = value;
			}
		}


		public SqlDateTime BIRTH_DAY
		{
			get
			{
				return _bIRTH_DAY;
			}
			set
			{
				SqlDateTime bIRTH_DAYTmp = (SqlDateTime)value;
				if(bIRTH_DAYTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("BIRTH_DAY", "BIRTH_DAY can't be NULL");
				}
				_bIRTH_DAY = value;
			}
		}


		public SqlString GIOI_TINH_YN
		{
			get
			{
				return _gIOI_TINH_YN;
			}
			set
			{
				SqlString gIOI_TINH_YNTmp = (SqlString)value;
				if(gIOI_TINH_YNTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("GIOI_TINH_YN", "GIOI_TINH_YN can't be NULL");
				}
				_gIOI_TINH_YN = value;
			}
		}


		public SqlDecimal LEVEL_MODE
		{
			get
			{
				return _lEVEL_MODE;
			}
			set
			{
				SqlDecimal lEVEL_MODETmp = (SqlDecimal)value;
				if(lEVEL_MODETmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("LEVEL_MODE", "LEVEL_MODE can't be NULL");
				}
				_lEVEL_MODE = value;
			}
		}
		#endregion
	}
}
