///************************************************
/// Generated by: TUAN_BH
/// Date: 29/03/2015 06:59:20
/// Goal: Create User Service Class for DM_LOP_HOC
///************************************************
/// <summary>
/// Create User Service Class for DM_LOP_HOC
/// </summary>

namespace BKITrainingUS
{
using BKITrainingDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using System;


public class US_DM_LOP_HOC : US_Object
{
	private const string c_TableName = "DM_LOP_HOC";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_LOP 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_LOP", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_LOP"] = value;
		}
	}

	public bool IsMA_LOPNull() 
	{
		return pm_objDR.IsNull("MA_LOP");
	}

	public void SetMA_LOPNull() {
		pm_objDR["MA_LOP"] = System.Convert.DBNull;
	}

	public string strTEN_LOP 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_LOP", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_LOP"] = value;
		}
	}

	public bool IsTEN_LOPNull() 
	{
		return pm_objDR.IsNull("TEN_LOP");
	}

	public void SetTEN_LOPNull() {
		pm_objDR["TEN_LOP"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_LOP_HOC() 
	{
		pm_objDS = new DS_DM_LOP_HOC();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_LOP_HOC(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_LOP_HOC(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_LOP_HOC();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
}
}
